/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/28/2016
 */
package com.telstra.api;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.telstra.com/v1";

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static String oAuthAccessToken = "TODO: Replace";

}
