/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/28/2016
 */
package com.telstra.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AuthenticationResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5315679614703267918L;
    private String accessToken;
    private String expiresIn;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("access_token")
    public String getAccessToken ( ) { 
        return this.accessToken;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("access_token")
    public void setAccessToken (String value) { 
        this.accessToken = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("expires_in")
    public String getExpiresIn ( ) { 
        return this.expiresIn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("expires_in")
    public void setExpiresIn (String value) { 
        this.expiresIn = value;
    }
 
}
 