/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/28/2016
 */
package com.telstra.api.models;

import java.util.*;

public class GetAuthenticationInputBuilder {
    //the instance to build
    private GetAuthenticationInput getAuthenticationInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetAuthenticationInputBuilder() {
        getAuthenticationInput = new GetAuthenticationInput();
    }

    public GetAuthenticationInputBuilder clientId(String clientId) {
        getAuthenticationInput.setClientId(clientId);
        return this;
    }

    public GetAuthenticationInputBuilder clientSecret(String clientSecret) {
        getAuthenticationInput.setClientSecret(clientSecret);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetAuthenticationInput build() {
        return getAuthenticationInput;
    }
}