/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/28/2016
 */
package com.telstra.api.models;

import java.util.*;

public class MessageStatusBuilder {
    //the instance to build
    private MessageStatus messageStatus;

    /**
     * Default constructor to initialize the instance
     */
    public MessageStatusBuilder() {
        messageStatus = new MessageStatus();
    }

    public MessageStatusBuilder receivedTimestamp(String receivedTimestamp) {
        messageStatus.setReceivedTimestamp(receivedTimestamp);
        return this;
    }

    public MessageStatusBuilder sentTimestamp(String sentTimestamp) {
        messageStatus.setSentTimestamp(sentTimestamp);
        return this;
    }

    public MessageStatusBuilder status(ResponseStatusEnum status) {
        messageStatus.setStatus(status);
        return this;
    }

    public MessageStatusBuilder to(String to) {
        messageStatus.setTo(to);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MessageStatus build() {
        return messageStatus;
    }
}