/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/28/2016
 */
package com.telstra.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MessageResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5219864376327809032L;
    private String acknowledgedTimestamp;
    private String content;
    private String from;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("acknowledgedTimestamp")
    public String getAcknowledgedTimestamp ( ) { 
        return this.acknowledgedTimestamp;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("acknowledgedTimestamp")
    public void setAcknowledgedTimestamp (String value) { 
        this.acknowledgedTimestamp = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("content")
    public String getContent ( ) { 
        return this.content;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("content")
    public void setContent (String value) { 
        this.content = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("from")
    public String getFrom ( ) { 
        return this.from;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("from")
    public void setFrom (String value) { 
        this.from = value;
    }
 
}
 