/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/28/2016
 */
package com.telstra.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum ResponseStatusEnum {
    PEND, //The message is pending and has not yet been sent to the intended recipient
    SENT, //The message has been sent to the intended recipient, but has not been delivered yet
    DELIVRD, //The message has been delivered to the intended recipient
    READ; //The message has been read by intended recipient and the recipient's response has been received

    private static TreeMap<String, ResponseStatusEnum> valueMap = new TreeMap<String, ResponseStatusEnum>();
    private String value;

    static {
        PEND.value = "PEND";
        SENT.value = "SENT";
        DELIVRD.value = "DELIVRD";
        READ.value = "READ";

        valueMap.put("PEND", PEND);
        valueMap.put("SENT", SENT);
        valueMap.put("DELIVRD", DELIVRD);
        valueMap.put("READ", READ);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ResponseStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ResponseStatusEnum values to list of string values
     * @param toConvert The list of ResponseStatusEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<ResponseStatusEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (ResponseStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 