/*
 * TelstraSMSAUSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/28/2016
 */
package com.telstra.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SendMessageResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4688459830666349017L;
    private String messageId;
    /** GETTER
     * The unique id to identity the message sent.
     */
    @JsonGetter("messageId")
    public String getMessageId ( ) { 
        return this.messageId;
    }
    
    /** SETTER
     * The unique id to identity the message sent.
     */
    @JsonSetter("messageId")
    public void setMessageId (String value) { 
        this.messageId = value;
    }
 
}
 